name: Action that only runs manually

on:
  pull_request:

jobs:
  log-message:
    runs-on: ubuntu-latest
    steps:
      - name: Log message to console
        run: echo 'This action was triggered manually'
        shell: bash